//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimplePaymentReminderDataAccessNF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReminder
    {

        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerNumber { get; set; }
        public string Comment { get; set; }
        public string ImageURL { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
